# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Evulving
email: zestyroxy@gmail.com
owner: Roxanne Joncas
description: >- # this means to ignore newlines until "baseurl:"
  What it means to be born a girl in a sexist world
url: "https://www.normalyouare.com" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

social:
  twitter: https://twitter.com/evulving
  instagram: https://www.instagram.com/evulving
  email: mailto:zestyroxy@gmail.com
  #youtube-square: https://www.youtube.com/channel/UC3u3YZ35NU1Zl3zxRH3d7OA
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>

# Build settings
markdown: kramdown
